import numpy as np
arr = np.load("adjacency_matrix.npy")
print(arr.shape)
print("********************************")
arr = np.load("influence_feature.npy")
print(arr.shape)
print("********************************")
arr = np.load("vertex_feature.npy")
print(arr.shape)
print("********************************")
arr = np.load("vertex_id.npy")
print(arr.shape)
print("********************************")
arr = np.load("label.npy")
print(arr.shape)
print("********************************")
print("load .npy done")